"""
Investigation model — a single RCA investigation run for an Incident.
Stores the full investigation plan, per-signal findings, tool call history,
and the final RCA markdown report.
"""
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime, Enum, Float, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.incident import Incident


class Investigation(Base):
    """
    A single investigation run.  One Incident can have many Investigation runs
    (re-investigate, investigate with different context, etc.).
    """

    __tablename__ = "investigations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        comment="Investigation UUID",
    )
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        comment="Parent incident UUID",
    )
    status: Mapped[str] = mapped_column(
        Enum(
            "pending",
            "running",
            "completed",
            "failed",
            name="investigation_status",
        ),
        nullable=False,
        default="pending",
        comment="Investigation lifecycle status",
    )
    plan: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        comment="Investigation plan generated by the Planner agent",
    )
    findings: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        comment="Per-signal findings keyed by agent name (metrics/logs/traces/...)",
    )
    rca: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Final RCA markdown report produced by the Synthesizer agent",
    )
    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Synthesizer confidence score 0.0–1.0",
    )
    tool_calls: Mapped[Optional[list]] = mapped_column(
        JSON,
        nullable=True,
        default=list,
        comment="Full ordered list of tool calls executed during investigation",
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the investigation started running",
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="When the investigation finished (success or failure)",
    )
    created_by: Mapped[str] = mapped_column(
        String(256),
        nullable=False,
        default="system",
        comment="Who triggered this investigation (user email or 'system:auto')",
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Error details if the investigation failed",
    )

    # --- Relationships ---
    incident: Mapped["Incident"] = relationship(
        "Incident",
        back_populates="investigations",
    )

    def __repr__(self) -> str:
        return (
            f"<Investigation id={self.id} status={self.status} "
            f"incident_id={self.incident_id}>"
        )
